Dashboard/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('', home, name='home'),
    path('Users/user_view', all_user, name='all_user'),
    path('Users/Add', add_user, name='add_user'),
    path('Items/All', all_products_view, name='all_products_view'),
    path('Items/Add', create_item, name='create_item'),
    path('Invoice/All', all_invoice_list, name='all_invoice_list'),
    path('Invoice/View/<id>', single_invoice, name='single_invoice'),

]

Login/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('login', login, name='login'),
    path('logout', logout, name='logout')
]

RobinHoodAdmin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Dashboard.urls', 'Dashboard'), namespace='Dashboard')),
    path('User/', include(('Login.urls', 'Login'), namespace='User')),
]

Dashboard/models.py
from django.db import models

# Create your models here.

Dashboard/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from API.FirebaseConsole import get_all_users, create_user, add_item, get_all_products, get_all_invoices, get_single_invoice
from django.contrib import messages


def home(request):
    try:
        if request.session['username']:
            print('ALL OK')
        else:
            return redirect('User:login')
    except:
        return redirect('User:login')
    return render(request, 'dashboard/dashboard.html')

def check_login(request):
    try:
        if request.session['username']:
            print('ALL OK')
        else:
            return redirect('Dashboard:login')
    except:
        return redirect('Dashboard:login')

def all_user(request):
    user_list = get_all_users()
    context = {
        'user_list': user_list
    }

    return render(request, 'user/view_user.html', context=context)

def add_user(request):

    if request.method == 'POST':
        try:
            Username = request.POST.get('Username')
            Password = request.POST.get('Password')

            fb = create_user(Username, Password)
            if fb:
                messages.add_message(request, messages.SUCCESS, 'User Created')
            else:
                messages.add_message(request, messages.SUCCESS, 'User Exist')
        except:
            messages.add_message(request, messages.ERROR, 'Input Error')


    context = {
    }

    return render(request, 'user/add_user.html', context=context)

def create_item(request):

    if request.method == 'POST':
        try:
            name = request.POST.get('name')
            cost = float(request.POST.get('cost'))

            add_item(name, cost)

            messages.add_message(request, messages.SUCCESS, 'Product Added')

        except:
            messages.add_message(request, messages.ERROR, 'Input Error')


    context = {
    }

    return render(request, 'Clinic/add_item.html', context=context)

def all_products_view(request):
    product_list = get_all_products()
    context = {
        'product_list': product_list
    }

    return render(request, 'Clinic/view_items.html', context=context)

def all_invoice_list(request):
    invoice_list = get_all_invoices()

    context = {
        'invoice_list':invoice_list
    }

    return render(request, 'Clinic/all_invoices.html', context=context)

def single_invoice(request, id):
    invoice = get_single_invoice(id)

    if not invoice == None:

        context = {
            'invoice': invoice
        }
        print(invoice)
        return render(request, 'Clinic/invoice.html', context=context)
    else:
        return render(request, 'Clinic/not_found.html')

Login/views.py
from django.shortcuts import render
from API.FirebaseConsole import find_admin_user
from django.contrib import messages
from django.shortcuts import render, redirect

def login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        admin_user = find_admin_user(username)

        if admin_user == None:
            messages.add_message(request, messages.ERROR, 'User Not Found')
            return render(request, 'Login/login.html')
        else:
            if admin_user['password'] == password:
                request.session['username'] = username
                return redirect('Dashboard:home')
            else:
                messages.add_message(request, messages.ERROR, 'Wrong Credentials')
            return render(request, 'Login/login.html')


    else:
        return render(request, 'Login/login.html')

def logout(request):
    request.session['username'] = None
    return redirect('Login:login')

templates/Clinic/add_item.html
{% extends 'base.html' %}

{% block title %}Add Product{% endblock %}

{% block body %}
<!-- ============================================================== -->
<!-- basic form  -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">Add Product</h5>
            <p>
                <div class="mx-auto" style="color:red">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </p>
            <div class="card-body">
                <form action="{% url 'Dashboard:create_item' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name" class="col-form-label">Product Name</label>
                        <input id="name" type="text" placeholder="Product Name" name="name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="cost">Cost (BDT)</label>
                        <input id="cost" name="cost" type="number" placeholder="Cost (BDT)" class="form-control">
                    </div>
                    <button class="btn btn-warning" type="submit">Add</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end basic form  -->
<!-- ============================================================== -->
<!-- ============================================================== -->


{% endblock %}

templates/Clinic/all_invoices.html
{% extends 'base.html' %}

{% block title %}User List{% endblock %}

{% block body %}
<div class="row">

    <!-- ============================================================== -->
    <!-- basic table  -->
    <!-- ============================================================== -->
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">All Invoice</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered first">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Customer</th>
                            <th>Bill (Method)</th>
                            <th>Invoice by</th>
                            <th>Time</th>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for invoice in invoice_list %}
                        <tr>
                            <td>{{invoice.id}}</td>
                            <td>{{invoice.CUSTOMER_NAME}} <span>&#9742;</span> {{invoice.CUSTOMER_PHONE}}</td>
                            <td>{{invoice.totalBill}} ({{invoice.paymentMethod}})</td>
                            <td>{{invoice.invoiceBy}}</td>
                            <td>{{invoice.time}}</td>
                            <td><a href="{% url 'Dashboard:single_invoice' id=invoice.id %}" class="btn btn-warning">View</a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Customer</th>
                            <th>Bill (Method)</th>
                            <th>Invoice by</th>
                            <th>Time</th>
                            <td></td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end basic table  -->
    <!-- ============================================================== -->

</div>



{% endblock %}

templates/Clinic/invoice.html
{% extends 'base.html' %}

{% block title %}Invoice #{{invoice.id}}{% endblock %}

{% block body %}

<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="section-block" id="cards">
            <h3 class="section-title">Invoice No. #{{invoice.id}}</h3>
            <p></p>
        </div>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Name: {{invoice.CUSTOMER.name}}</h3>
                <h3 class="card-title">Phone: {{invoice.CUSTOMER.phone}}</h3>
                <h3 class="card-title">Address: {{invoice.CUSTOMER.address}}</h3>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Date: {{invoice.time}}</h3>
                <h3 class="card-title">Payment: {{invoice.paymentMethod}}</h3>
                <h3 class="card-title">Ref No: {{invoice.id}}</h3>
            </div>
        </div>
    </div>
</div>

<div class="row">

    <!-- ============================================================== -->
    <!-- basic table  -->
    <!-- ============================================================== -->
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">All Items</h5>
            <div class="card-body">
                <div class="table">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Item</th>
                            <th>Quantity</th>
                            <th>Cost</th>
                            <th>Bill</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in invoice.ITEM_LIST %}
                        <tr>
                            <td>{{item.name}}</td>
                            <td>{{item.quantity}}</td>
                            <td>{{item.cost}}</td>
                            <td>{{item.total}}</td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td></td>
                            <td><strong>Total</strong></td>
                            <td>{{invoice.totalBill}}</td>
                        </tr>
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end basic table  -->
    <!-- ============================================================== -->

</div>



{% endblock %}

templates/Clinic/view_items.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}

{% block body %}
<div class="row">

    <!-- ============================================================== -->
    <!-- basic table  -->
    <!-- ============================================================== -->
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">All Products</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered first">
                        <thead>
                        <tr>
                            <th>UID</th>
                            <th>Name</th>
                            <th>Cost</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for pro in product_list %}
                        <tr>
                            <td>{{pro.id}}</td>
                            <td>{{pro.name}}</td>
                            <td>{{pro.cost}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>UID</th>
                            <th>Username</th>
                            <th>Password</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end basic table  -->
    <!-- ============================================================== -->

</div>



{% endblock %}

templates/Login/login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'main/assets/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'main/assets/vendor/fonts/circular-std/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/assets/libs/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/assets/vendor/fonts/fontawesome/css/fontawesome-all.css' %}">
    <link rel="stylesheet" href="{% static 'main/assets/vendor/vector-map/jqvmap.css' %}">
    <link rel="icon" href="{% static 'images/logo/robinhood.png' %}" type = "image/x-icon">
    <title>RobinHood: login</title>
</head>

<body>
    <div class="container">
        <div class="text-center">
            <div class="row">
                <div class="col-12" style="height:100px;"></div>
                <div class="col-12">
                    <img src="{% static 'images/logo/robinhood.png' %}" width="300" height="300">
                </div>
                <div class="col-12" style="height:100px;"></div>
                <div class="mx-auto" style="color:red">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                <div class="col-12">
                    <form action="{% url 'User:login' %}" method="POST">
                        {% csrf_token %}
                      <label for="username">Username:</label><br>
                      <input type="text" id="username" name="username"><br>
                      <label for="password">Password:</label><br>
                      <input type="password" id="password" name="password"><br><br>
                      <input type="submit" value="Login" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>

</body>

templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% block title %}RobinHood{% endblock %}

templates/user/add_user.html
{% extends 'base.html' %}

{% block title %}Create User{% endblock %}

{% block body %}
<!-- ============================================================== -->
<!-- basic form  -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">Create User</h5>
            <p>
                <div class="mx-auto" style="color:red">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </p>
            <div class="card-body">
                <form action="{% url 'Dashboard:add_user' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="Username" class="col-form-label">Username</label>
                        <input id="Username" type="text" placeholder="Username" name="Username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="Password">Password</label>
                        <input id="Password" name="Password" type="password" placeholder="Password" class="form-control">
                    </div>
                    <button class="btn btn-primary" type="submit">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- end basic form  -->
<!-- ============================================================== -->
<!-- ============================================================== -->


{% endblock %}

templates/user/view_user.html
{% extends 'base.html' %}

{% block title %}User List{% endblock %}

{% block body %}
<div class="row">

    <!-- ============================================================== -->
    <!-- basic table  -->
    <!-- ============================================================== -->
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <h5 class="card-header">All App User</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered first">
                        <thead>
                        <tr>
                            <th>UID</th>
                            <th>Username</th>
                            <th>Password</th>
                            <th>Last Login</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in user_list %}
                        <tr>
                            <td>{{user.id}}</td>
                            <td>{{user.username}}</td>
                            <td>{{user.password}}</td>
                            <td>{{user.lastLogin}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>UID</th>
                            <th>Username</th>
                            <th>Password</th>
                            <th>Last Login</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end basic table  -->
    <!-- ============================================================== -->

</div>



{% endblock %}